version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 10
    # Enable version updates for pnpm
    # Dependabot supports pnpm since 2023
    versioning-strategy: increase
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'ci(deps)'
